spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: admin
  jpa:
    show-sql: true
  liquibase:
    change-log: classpath:db/changelog/liquibase-changeLog.xml